# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
a = torch.rand(7,7)


tensor([[6.1838e-01, 9.3573e-01, 1.1197e-01, 2.8263e-01, 6.7238e-01, 3.8461e-01,
         3.1611e-01],
        [3.7400e-01, 2.5667e-01, 2.5278e-01, 6.6125e-01, 6.6975e-01, 9.9470e-01,
         4.7845e-01],
        [9.9010e-01, 5.6842e-01, 2.0613e-01, 1.3003e-01, 4.3845e-01, 4.9662e-01,
         8.7860e-01],
        [3.1243e-02, 3.5660e-01, 4.6494e-02, 6.4358e-01, 2.5416e-01, 9.9758e-01,
         9.6302e-01],
        [2.2366e-01, 7.6624e-01, 5.6345e-01, 8.0156e-04, 2.7898e-01, 3.2646e-01,
         5.0432e-01],
        [5.9656e-01, 9.3802e-01, 1.4202e-01, 4.5736e-01, 3.1658e-01, 2.7415e-01,
         9.8658e-02],
        [3.9034e-02, 3.8146e-01, 1.5663e-01, 1.3883e-01, 4.8619e-01, 7.5561e-01,
         8.1822e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
b = torch.rand(1,7)

# Perform matrix multiplication
a_mul = a.mm(b.T)
print(a_mul)
print(a_mul.shape)

torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
import random
torch.manual_seed(0)

# Create two random tensors
a = torch.rand(7,7)
b = torch.rand(1,7)

# Matrix multiply tensors
a_mul = a.mm(b.T)
print(a_mul)
print(a_mul.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)        # seeds the current GPU
torch.cuda.manual_seed_all(1234)    # seeds ALL GPUs (for multi-GPU setups)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
a = torch.rand(2,3).to(device)
b = torch.rand(2,3).to(device)
print("Device:",device)
print(a)
print(b)


Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
a_mul = a.mm(b.T)
print(a_mul)
print(a_mul.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
max = a_mul.max()
print(max)
# Find min
min = a_mul.min()
print(min)


tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
argmax = a_mul.argmax()
print(argmax)

# Find arg min
argmin = a_mul.argmin()
print(argmin)

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(7)

# Create random tensor
a = torch.rand(1,1,1,10)

# Remove single dimensions
final_a = torch.squeeze(a)

# Print out tensors and their shapes
print(a, a.shape)
print(final_a, final_a.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
