## Tensor Basics

In [8]:
import torch
import numpy as np

In [10]:
#creating tensor
x = torch.empty(2,3) # 2x3 Matrix
print(x)

# creating tensor with random values
x = torch.rand(2,2)
print(x)

# zero tensors
x = torch.zeros(2,2)
print(x)
print(x.dtype) # to get the type of the values

# changing types
x = torch.rand(2,2,dtype = torch.float16)
print(x.dtype)


x = torch.tensor([2.5,0.1])
print(x)

tensor([[7.4157e+28, 4.4860e-41, 1.5185e-06],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])
tensor([[0.9874, 0.7972],
        [0.1894, 0.5160]])
tensor([[0., 0.],
        [0., 0.]])
torch.float32
torch.float16
tensor([2.5000, 0.1000])


In [13]:
# Basic Operations
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y  # z = torch.add(x,y)    -     y.add_(x) - they all do the same thing
print(z)
z = x - y  # z = torch.sub(x,y)
print(z)
z = x * y  # z = torch.mul(x,y)
print(z)
z = x / y  # z = torch.div(x,y)
print(z)

tensor([[0.3222, 0.1894],
        [0.9480, 0.2489]])
tensor([[0.7720, 0.1718],
        [0.5842, 0.7511]])
tensor([[1.0943, 0.3612],
        [1.5322, 1.0000]])
tensor([[-0.4498,  0.0175],
        [ 0.3638, -0.5022]])
tensor([[0.2488, 0.0325],
        [0.5538, 0.1869]])
tensor([[0.4174, 1.1021],
        [1.6228, 0.3314]])
tensor([0.1361, 0.9844, 0.5156])


In [18]:
x = torch.rand(3,5)
print(x)
print(x[:,0])  # print all rows of first column
print(x[1,:])  # print all the elements in second row
# we can use x[1,1].item if we are pointing to a single element

# Reshaping
x = torch.rand(4,4)
print(x)
y = x.view(16)   # we can use -1 as an input so torch itself will determine the size
print(y)

tensor([[0.8766, 0.8326, 0.1250, 0.9131, 0.0931],
        [0.6816, 0.9182, 0.8400, 0.5964, 0.7798],
        [0.1814, 0.5014, 0.6249, 0.8267, 0.4249]])
tensor([0.8766, 0.6816, 0.1814])
tensor([0.6816, 0.9182, 0.8400, 0.5964, 0.7798])
tensor([[0.9309, 0.8558, 0.1067, 0.3069],
        [0.0836, 0.9795, 0.1914, 0.7797],
        [0.6684, 0.9818, 0.7034, 0.5691],
        [0.3132, 0.2571, 0.0131, 0.0964]])
tensor([0.9309, 0.8558, 0.1067, 0.3069, 0.0836, 0.9795, 0.1914, 0.7797, 0.6684,
        0.9818, 0.7034, 0.5691, 0.3132, 0.2571, 0.0131, 0.0964])


In [23]:
# convert from np to torch and vice versa

# Tensor to Numpy
a = torch.ones(5)
print(a)
b = a.numpy()  # numpy can only handle cpu tensors and it gives and error for gpu tensors(cuda)
print(type(b))
print(b)
a.add_(1)
print(a)
print(b) # change in a will make a change on b  because they are both pointing into the same memory location , it only happens if the tensor is on CPU

# Numpy to Tensor
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
np.add(a, 1, out=a)
print(a)
print(b)


x = torch.ones(5, requires_grad=True) # by default requires_grad is False, track all operations on this tensor so I can compute gradients with respect to it later
print(x)



tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], requires_grad=True)
